import org.code.neighborhood.*;

public class KirbyPainter extends MuralPainter {

  public void drawKirby() {
   drawOutline();
   drawShoes();
   drawBody();
   drawShade();
   drawFace();
  }

  public void drawOutline() {
// Paints the black outline of Kirby
    setPaint(100);
    move();
    move();
    paint("black");
    move();
    paint("black");
    turnRight();
    move();
    move();
    paint("black");
    turnLeft();
    move();
    turnLeft();
    move();
    paint("black");
    move();
    turnRight();
    move();
    paintLine("black", 5);
    turnRight();
    move();
    turnLeft();
    setPaint(100);
    paint("black");
    move();
    paint("black");
    move();
    turnRight();
    move();
    paint("black");
    move();
    turnLeft();
    move();
    paint("black");
    turnRight();
    move();
    paint("black");
    move();
    turnLeft();
    move();
    paint("black");
    move();
    turnRight();
    move();
    paintLine("black", 3);
    move();
// Paints outline of Left Shoe
    paintLine("black", 3);
    turnRight();
    setPaint(100);
    move();
    paint("black");
    turnLeft();
    move();
    turnRight();
    move();
    paint("black");
    turnLeft();
    move();
    turnRight();
    move();
    paintLine("black", 3);
    setPaint(100);
    turnRight();
    move();
    move();
    paint("black");
    move();
    turnRight();
    move();
    turnLeft();
    paint("black");
    move();
    paint("black");
    turnRight();
    move();
    turnLeft();
    move();
    paint("black");
    turnRight();
    move();
    turnLeft();
    move();
    turnRight();
    paintLine("black", 3);
// moves to position
    turnRight();
    move();
    move();
    move();
    move();
    move();
    turnRight();
    move();
    move();
    move();
    move();
    move();
// paints the Right Shoe
    paintLine("black", 5);
    turnRight();
    move();
    turnLeft();
    setPaint(100);
    paint("black");
    move();
    paint("black");
    move();
    turnRight();
    move();
    turnLeft();
    paint("black");
    move();
    paint("black");
    move();
    turnLeft();
    move();
    paint("black");
    turnRight();
    move();
    turnLeft();
    move();
    paint("black");
    move();
    turnLeft();
    move();
    paintLine("black", 6);
//moves back to position
    turnLeft();
    move();
    move();
    move();
    move();
    turnLeft();
    move();
    move();
    move();
    move();
    move();
    turnRight();
//finishes outline
    setPaint(100);
    paint("black");
    move();
    turnLeft();
    move();
    turnRight();
    paintLine("black", 3);
    turnLeft();
    move();
    turnRight();
    paintLine("black", 6);
    turnRight();
    move();
    setPaint(100);
    paint("black");
  }

 public void drawShoes() {
   //moves to position
   turnRight();
   moveFast();
   turnLeft();
   turnLeft();
   move();
   turnRight();
   //paints right shoe
   paintLine("red", 5);
   turnLeft();
   move();
   turnLeft();
   move();
   move();
   move();
   setPaint(100);
   paint("red");
   move();
   paint("white");
   //moves to left Shoe
   turnLeft();
   turnLeft();
   moveFast();
   turnRight();
   move();
   turnRight();
   move();
   move();
   move();
   //Paints Right shoe
   paintLine("red", 2);
   turnRight();
   move();
   turnRight();
   paintLine("red", 4);
   turnLeft();
   move();
   turnLeft();
   paintLine("red", 4);
   turnRight();
   move();
   turnRight();
   move();
   paintLine("red", 4);
   turnLeft();
   move();
   turnLeft();
   move();
   paintLine("red", 3);
 } 

  public void drawBody() {
//moves to position
    moveFast();
    turnRight();
    moveFast();
    turnRight();
    turnRight();
    move();
    turnLeft();
    move();
    move();
//paints body
    setPaint(100);
    paint("pink");
    move();
    paint("pink");
    move();
    move();
    paintLine("pink",5);
    move();
    turnRight();
    move();
    turnRight();
    paintLine("pink", 8);
    move();
    setPaint(100);
    paintLine("pink", 2);
    turnLeft();
    move();
    turnLeft();
    move();
    paintLine("pink", 12);
    turnRight();
    move();
    turnRight();
    move();
    paintLine("pink", 12);
    turnLeft();
    move();
    turnLeft();
    move();
    paintLine("pink", 13);
    turnRight();
    move();
    turnRight();
    paintLine("pink", 14);
    turnLeft();
    move();
    turnLeft();
    move();
    paintLine("pink", 14);
    turnRight();
    move();
    turnRight();
    move();
    paintLine("pink", 13);
    turnLeft();
    move();
    turnLeft();
    move();
    paintLine("pink", 10);
    turnRight();
    move();
    turnRight();
    move();
    move();
    paintLine("pink", 9);
    turnLeft();
    move();
    turnLeft();
    move();
    move();
    paintLine("pink", 7);
    turnRight();
    move();
    turnRight();
    move();
    paintLine("pink", 6);
    turnLeft();
    move();
    turnLeft();
    move();
    move();
    move();
    paintLine("pink", 3);
  }
 
  public void drawShade() {
  //paints the shadow on kirby
    turnLeft();
    move();
    paintLine("paleVioletRed", 2);
    turnRight();
    move();
    setPaint(100);
    paint("paleVioletRed");
    turnLeft();
    move();
    turnRight();
    move();
    paint("paleVioletRed");
    turnLeft();
    move();
    turnRight();
    move();
    paintLine("paleVioletRed", 2);
    turnLeft();
    paintLine("paleVioletRed", 3);
    turnLeft();
    move();
    setPaint(100);
    paint("paleVioletRed");
    move();
    turnRight();
    move();
    paintLine("paleVioletRed", 2);
    turnLeft();
    move();
    paintLine("paleVioletRed", 2);
    turnRight();
    move();
    setPaint(100);
    paint("paleVioletRed");
    turnLeft();
    move();
    move();
    move();
    move();
    paint("paleVioletRed");
    turnLeft();
    move();
    turnRight();
    move();
    paint("paleVioletRed");
    move();
    move();
    move();
    turnLeft();
    paintLine("paleVioletRed", 6);
    turnLeft();
    move();
    turnRight();
    paintLine("paleVioletRed", 3);
    turnLeft();
    move();
    setPaint(100);
    paint("paleVioletRed");
    move();
    turnRight();
    move();
    turnLeft();
    paintLine("paleVioletRed", 2);
    turnRight();
    move();
    turnLeft();
    paintLine("paleVioletRed", 3);
  }

 public void drawFace() {
  //move to possition
   turnLeft();
   moveFast();
   turnLeft();
   move();
   turnLeft();
   move();
   move();
//paints kirby's face
   //left Eye and cheek
   paintLine("black", 3);
   turnLeft();
   move();
   paintLine("hotPink", 2);
   turnLeft();
   turnLeft();
   move();
   move();
   move();
   move();
   move();
   move();
   //right eye and cheek
   paintLine("hotPink", 2);
   turnRight();
   move();
   turnRight();
   move();
   move();
   move();
   turnLeft();
   paintLine("black", 3);
   turnRight();
   move();
   turnRight();
   move();
   move();
   move();
   move();
   move();
   //mouth
   paintLine("black", 2);
 }
  
}